### ISSUE TITLE
Quick Launch cannot see "user" Flatpaks

### ISSUE THREAD

**Issue by ubergeek77** [Fisch03/SDH-QuickLaunch#10]
Flatpaks that have been installed as `user` packages are not listed - only Flatpaks installed as `system` packages are showing up in Quick Launch.

For instance, all of the emulators from EmuDeck are installed as `user` packages, but none of them are showing up in Quick Launch. I also have a few other `user` Flatpaks that don't show up in the list.

I'm not sure if this has always been the case, or if this is a recent bug in SteamOS 3.5. Please let me know if I can help gather logs or something!

**Comment by Fisch03** [comment]
Hi! Sorry for not getting to you earlier. I already have a slight suspicion as to why that would be a thing, but I'll have a closer look at it. 
I unfortunately don't have access to my deck in the upcoming week or so but i'll try to get to it asap :)

**Comment by Fisch03** [comment]
Finally got around to fixing this, the upcoming update should include both global and decky user flatpaks in the list!
