### ISSUE TITLE
Only Cancel button appears in Select App dropdown

### ISSUE THREAD

**Issue by miausterhunter** [Fisch03/SDH-QuickLaunch#13]
I installed the plug-in from the store, but no applications appear selectable from the dropdown menu and no shortcuts can be created.

Decky v2.12.3
Steam 3.5.19 Beta

**Comment by Fisch03** [comment]
Thanks for the report! Unfortunately I am unable to reproduce this even with the exact versions you specified :(

A few questions: Did you try to reboot your deck after the installation? And does it change anything if you enable the "Launch all Apps" Toggle?

**Comment by miausterhunter** [comment]
I was able to resolve it. I uninstalled it, went into desktop mode and deleted all the related quick launch folders from the homebrew folder, then reinstalled it. Now it works and the flatpak/file options appear properly. 

Thanks for looking into it and making such a cool plug-in!
