### ISSUE TITLE
Support non Flatpak Apps

### ISSUE THREAD

**Issue by JakobDev** [Fisch03/SDH-QuickLaunch#3]
Would be nice, if you could add Support for all Apps. Just parse the .desktop files. Launch with `kioclient5 exec <path_to_desktop_file>`.

**Comment by Fisch03** [comment]
Hi, this is actually something i have already got (kind of) working. Unfortunately the DeckUI has some very wierd behaviour when you quickly update Shortcuts with arbitrary Programs (that are not flatpaks). I have not tried it with kioclient yet, so that might be worth a shot.

**Comment by Fisch03** [comment]
With the new Release the Plugin supports launching everything from the Start Menu, closing this as completed.
