### ISSUE TITLE
plugin stays on "fetching packages..."

### ISSUE THREAD

**Issue by ParisGreen** [Fisch03/SDH-QuickLaunch#4]
Am I missing a step in getting this started?

**Comment by Fisch03** [comment]
What version of the Plugin Loader are you using? The plugin unfortunately doesn't work with the new one (Decky) for now. I already have a completely rewritten working version in place but haven't gotten around to submitting in to the Store yet...

**Comment by zany130** [comment]
Is there a way to manually add it? I tried extracting the zip into the plugins folder, and it won't load

**Comment by Fisch03** [comment]
You'd have to manually compile it, but even then I can't guarantee that it will work flawlessly since it's already been a while since I developed the working version. I'm sure there have been some breaking changes in the meantime.

I am however almost free from my forced hiatus due to University exams so I should finally be able to get back to fixing things up in about a week. Sorry for the wait :)

**Comment by Fisch03** [comment]
Another quick Update on this: I have verified that most of the core functionality of the Plugin still works, I only have to fix a very small portion. Look forward to a release within hopefully the upcoming week!

**Comment by V-Tac** [comment]
Any update on this? Would love to get installed on my deck! Thanks!

**Comment by Fisch03** [comment]
Unfortunately not yet. I really wanted to get this out before the new Semester started but due to me actually moving i just couldn't find the time. Sorry it is taking so long but I promise It'll be there eventually. I really want to get this up and running again too.

**Comment by Andrew-R-Lawler** [comment]
> Unfortunately not yet. I really wanted to get this out before the new Semester started but due to me actually moving i just couldn't find the time. Sorry it is taking so long but I promise It'll be there eventually. I really want to get this up and running again too. 

I miss you and your plug-in. Please come back :(

**Comment by Fisch03** [comment]
Been quite a while huh? Im back! I finally got around to fixing up the plugin and its in working order again!! There's still some smaller kinks i need to work out but the vast majority is done. Sorry for taking soooo long and thank you all so much for all the uplifting messages i got here and elsewhere :D

**Comment by Fisch03** [comment]
And the Plugin is back on the store! Enjoy :)
